### ISSUE TITLE
Webapp error

### ISSUE THREAD

**Issue by Oratorian** [atomia/atomiadns#41]
i followed the guide @http://atomiadns.com/get-started/install-atomia-dns/

But when it comes to the webapp section everything starts going crazy

First : the command :start atomiadns-webapp its not found and not availale
Then i tried service atomiadns-webapp start and i get : `Failed to start atomiadns-webapp.service: Unit atomiadns-webapp.service not found.`

webapp seems install cause i can find the .js file in `/usr/lib/atomiadns/webapp/atomiadns.js`
Then tried tried to use : nodejs /usr/lib/atomiadns/webapp/atomiadns.js which errors out with : 

`/usr/lib/atomiadns/webapp/rest.js:11
        throw new Error("You have to specify the environment variable WEBAPP_NAMESERVERS, containing comma separated NS-records to use as default for new zones. Add something like this to /etc/atomiadns.conf:\nwebapp_nameservers=ns1.example.com,ns2.example.com");
Error: You have to specify the environment variable WEBAPP_NAMESERVERS, containing comma separated NS-records to use as default for new zones. Add something like this to /etc/atomiadns.conf:
webapp_nameservers=ns1.example.com,ns2.example.com
    at Object.<anonymous> (/usr/lib/atomiadns/webapp/rest.js:11:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/atomiadns/webapp/auth.js:4:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)`

I did enter  the webapp_nameservers= directive into the config file but still same error
I am running Ubuntu 16.04 Insta lling AtomiaDNS using the APT Repo worked fine until the steps for the webapp.

**Comment by stefan-stankovic-atomia** [comment]
Fixed in #46
